services:
  postgres:
    image: postgres:16
    container_name: query-monitor-postgres
    environment:
      POSTGRES_DB: query_monitor
      POSTGRES_USER: query_monitor
      POSTGRES_PASSWORD: query_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: query-monitor-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
