spring.application.name=query-monitor

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/query_monitor}
spring.datasource.username=${DB_USERNAME:query_monitor}
spring.datasource.password=${DB_PASSWORD:query_monitor}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
